ZAP
stfbk/mig-t pull request #14
Opened 2024-10-02 13:40 UTC by NickLech

ZAP files loaded

2024-10-02 14:42 UTC, mattebit requested changes

2024-10-02 14:42 UTC, mattebit commented on tool/.gitignore
Please avoid removing the gitignore

2024-10-02 14:42 UTC, mattebit commented on tool/src/test/java/At_Hash_Test.java
Why removing the tests?

2024-10-02 14:42 UTC, mattebit commented on tool/src/main/java/org/zaproxy/addon/migt/samlraider/model/ObjectIdentifier.java
The license of samlraider should not be edited or removed, you can append the ZAP one if needed, but i don't think it is needed for these files

2024-10-02 14:42 UTC, mattebit commented on tool/src/main/java/org/zaproxy/addon/migt/samlraider/helpers/XSWHelpers.java
Why is everything commented? if they're not needed just remove them, but please verify that SAML functionalities are mantained

2024-10-02 14:42 UTC, mattebit commented on tool/src/main/java/org/zaproxy/addon/migt/ZAPPrincipale.java
> +public class ZAPPrincipale extends ExtensionAdaptor implements ProxyListener {
Please avoid Italian

2024-10-02 14:42 UTC, mattebit commented on tool/src/main/java/org/zaproxy/addon/migt/ParsingException.java
Do the ZAP license need to be included in every file of the addon? please check if necessary. I would just put it in the code using ZAP libraries

2024-10-02 14:42 UTC, mattebit commented on tool/gradle/wrapper/gradle-wrapper.jar
Is there a way to avoid pushing gradle jar and binaries?

2024-10-02 14:42 UTC, mattebit commented on tool/CHANGELOG.md
> +- Addon creato nella cartela zap-extension
Please use english

2024-10-02 14:42 UTC, mattebit commented on tool/readme.md
Instead of deleting, it could be useful to provide info on how to do this in gradle

2024-10-02 15:06 UTC, NickLech commented on tool/migt.gradle.kts
Yes, at least for now the ZAP add-on build uses some specific functions that are given by the platform, in the future we may convert from one to another but for now we have to use them

2024-10-02 15:12 UTC, NickLech commented on tool/src/main/java/org/zaproxy/addon/migt/samlraider/model/ObjectIdentifier.java
ZAP was giving an error due to the lack of a license. I will try to re-add the samlaider licence, which was automatically removed by a built-in feature of ZAP that I used to update the licenses.

2024-10-02 15:52 UTC, NickLech commented on tool/src/main/java/org/zaproxy/addon/migt/samlraider/helpers/XSWHelpers.java
I will remove everything commented, I left it there just in case we wanted some of those functions but we can add them if needed

2024-10-02 15:53 UTC, NickLech commented on tool/src/test/java/At_Hash_Test.java
I forgot to add them, this was another implementation, I will put them back in

2024-10-02 16:18 UTC, NickLech commented on tool/src/main/java/org/zaproxy/addon/migt/ZAPPrincipale.java
> +public class ZAPPrincipale extends ExtensionAdaptor implements ProxyListener {
The italian should have been removed

2024-10-02 16:21 UTC, NickLech commented on tool/.gitignore
It shoud be present now

2024-10-02 16:34 UTC, NickLech commented on tool/src/main/java/org/zaproxy/addon/migt/samlraider/model/ObjectIdentifier.java
It does not allow me to build it if I have the other licence, I will search for a solution but for now could leave it like this, this branch was created so that I could send the link to the ZAP developers for an issue with the code

2024-10-03 09:30 UTC, mattebit commented on tool/gitignore.txt
the name should be ".gitignore"

2024-10-03 09:30 UTC, mattebit commented on tool/src/main/java/org/zaproxy/addon/migt/samlraider/model/ObjectIdentifier.java
Ok. The branch should already be visible, so I would wait to merge the PR until we asses this doubt

2024-10-03 10:14 UTC, NickLech commented
The issue is that we wanted to send the code for the ZAP plugin, so the branch needs to contain the code I submitted in the PR. Initially, I intended to send my repository, but it was later decided to create a dedicated branch for my code. If you think this is a problem, let me know, and I will ask the others how to proceed.

2024-10-04 08:48 UTC, NickLech commented
Hy, I was able to change the rules for the build and now the MIT license should be present as well as some changes in the build file

2024-10-04 09:36 UTC, mattebit commented
> Hy, I was able to change the rules for the build and now the MIT license should be present as well as some changes in the build file

Please then verify with ZAP developers that this is ok for them.

> The issue is that we wanted to send the code for the ZAP plugin, so the branch needs to contain the code I submitted in the PR. Initially, I intended to send my repository, but it was later decided to create a dedicated branch for my code. If you think this is a problem, let me know, and I will ask the others how to proceed.

I would just wait to merge and let them see your fork, but if @abisegna prefers to merge it is ok, but please do not marge into main until we asses these doubts

2024-10-04 09:38 UTC, mattebit approved these changes

2024-10-04 09:41 UTC, NickLech commented
Yes, I already asked them and they said: "The ZAP license header is only needed if you plan to contribute the
add-on and it will live in zap-extensions repo, otherwise you are free
to use whatever license you deem appropriate for your add-on. "

2024-10-04 14:05 UTC, merged

2024-10-04 15:02 UTC, mattebit commented
> Yes, I already asked them and they said: "The ZAP license header is only needed if you plan to contribute the add-on and it will live in zap-extensions repo, otherwise you are free to use whatever license you deem appropriate for your add-on. "

Ok. So you can remove the ZAP licence also from the mig-t files. The Saml Raider files must have their original license notice in their files